DROP TABLE IF EXISTS `log`;
CREATE TABLE `log` (
    `log_id` UNSIGNED INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `channel` VARCHAR(255) NOT NULL,
    `level` UNSIGNED INTEGER NOT NULL,
    `datetime` DATETIME NOT NULL,
    `message` LONGBLOB NOT NULL,
    `context` LONGBLOB NOT NULL,
    `extra` LONGBLOB NOT NULL
);
